### ISSUE TITLE
Curse of the Strong Survivors have some problems

### ISSUE THREAD

**Issue by tianjun2147483647** [divisionbyz0rro/Infiniscryption#38]
If I die only one, can the curse card become a squirrel card? I've been in that situation. I'm not sure.

**Comment by divisionbyz0rro** [comment]
Hi @tianjun2147483647; I'm not sure I understand your question. 

The Curse of the Strong Survivors changes two things about the campfire events:

1. If the survivors do not eat your card, the next time you come to a campfire they have a chance to eat your card on the first attempt.

2. If the survivors eat one of your cards, they may also take of your items. If you have a squirrel or goat in a bottle, they will take that first. If you don't have a card in a bottle, they will take your pliers. If you don't have pliers, they will take a knife. If you do not have a knife, then the chances of them eating your card next time go way up.

**Comment by divisionbyz0rro** [comment]
This will not be fixed or further investigated. With the upcoming release of Kaycee's Mod, this curse will be removed. Kaycee's Mod already fixes a lot of the problems with campfires to the point where this is no longer necessary.
