### ISSUE TITLE
Soft lock

### ISSUE THREAD

**Issue by PeaieceProductions** [divisionbyz0rro/Infiniscryption#39]
Soft lock when opponent plays totem with bird head, guardian sigil.
The totem head-turn animation is skipped if that helps.
Disabling the 'Visually Stackable Sigils' mod fixes the issue.

**Comment by divisionbyz0rro** [comment]
This issue was fixed in release 1.0.2
https://inscryption.thunderstore.io/package/Infiniscryption/Visually_Stackable_Sigils/
