### ISSUE TITLE
Soft Lock

### ISSUE THREAD

**Issue by PeaieceProductions** [divisionbyz0rro/Infiniscryption#40]
Empty table when entering a campfire.
Fixes after restarting the game.

Console:
[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Renderer.get_material () (at <3f8c35799b544274b189c23afcaaf82e>:0)
Infiniscryption.Curses.Sequences.CardStatBoostHardSequencer+<StatBoostSequence>d__2.MoveNext () (at <83e462a16d7c42bdb3b18eb2c3d292b4>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Infiniscryption.Curses.Patchers.CampfireHarder:SendToUpgradeShop(SpecialNodeHandler&, SpecialNodeData)
DiskCardGame.SpecialNodeHandler:StartSpecialNodeSequence(SpecialNodeData)
DiskCardGame.<TransitionTo>d__31:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by divisionbyz0rro** [comment]
I've had this issue reported before, but it's never been reproducible. 

I'm keeping this in the issue queue for the next time I work on Curses. I might be able to work out a more robust way to generate the campfire to prevent this from happening, but without being able to consistently reproduce the issue it's going to be hard to pin down exactly what's happening.

Somehow, the 'get_material()' function is failing, inside of the Renderer object. That's internal Unity stuff; it means something's not loaded right, but exactly what is hard to pin down.

**Comment by divisionbyz0rro** [comment]
I will not be doing further research on this.

Starter Decks will be deprecated when Kaycee's Mod is released, so there isn't much value in me figuring out what causes this to happen.
