### ISSUE TITLE
Problem with some cards.

### ISSUE THREAD

**Issue by Zagiman72** [divisionbyz0rro/Infiniscryption#49]
I'm using the VanillaDed mod to remove the vanilla cards, but when i turn on the sample cards option in the configs, i still get chimes, dams, smokes, bait buckets etc. but no "normal" cards. Also, my game just straight up crashes when i play "Go Fetch"

https://user-images.githubusercontent.com/83546976/148422304-20ca3c12-ace6-4283-81be-037c58d79adf.mp4

.

**Comment by divisionbyz0rro** [comment]
I'm going to guess there's some sort of mod incompatibility that I haven't accounted for here; can you send me the list of all mods that you currently have installed?

**Comment by Zagiman72** [comment]
BepInExPack_Inscryption by BepInEx
Mod Logo
API by API_dev
Mod Logo
VanillaDed by Arackulele
Mod Logo
Inscryption_Unofficial_Patch by UnofficialScrybePatches
Mod Logo
Spell_Card_Toolkit by Infiniscryption
Mod Logo
Make_Vanilla_Sigils_Stackable by Infiniscryption
Mod Logo
Visually_Stackable_Sigils by Infiniscryption
Mod Logo
JSONCardLoader by MADH95Mods
Mod Logo
SigilADay_julianperge by JulianMods
Mod Logo
Kopie_Adventurers_Book by Kopie
Mod Logo
HealthForAnts by JulianMods
Mod Logo
Side_Deck_Selector by Infiniscryption
Mod Logo
Mowzies_Mobs_Card_Expansion by Cheddar_Cheese
Mod Logo
SigilArtPatch by MADH95Mods
Mod Logo
Memez4Life_No_Deathcards by Memez4Life
Mod Logo
Pirate_Boss_Mod by IngoH
Mod Logo
Kopie_RuleBook_Expender by Kopie
Mod Logo
Smalltweak_Hammer by Kopie
Mod Logo
DraftingMod by PortaMods
Mod Logo
SigilADay by Cyantist
Mod Logo
ExtendedMaps by Cyantist

**Comment by divisionbyz0rro** [comment]
The latest API should theoretically have fixed the root cause of this issue, so getting the latest versions of both of these should solve the problem.
