### ISSUE TITLE
card creator compatibility?

### ISSUE THREAD

**Issue by scrybeofteeth** [divisionbyz0rro/Infiniscryption#50]
I'm wondering if there is a way to add the trait to cards made using the card creator plugin here: https://inscryption.thunderstore.io/package/IngoH/InGame_Card_Creator/

the layout of those files is like this, so trait numbers aren't functional:
{
  "name": "IGCC_looking_heart",
  "displayedName": "looking heart",
  "description": "a simple card to aid all others.",
  "metaCategories": [],
  "cardComplexity": "Simple",
  "temple": "Nature",
  "baseAttack": 0,
  "baseHealth": 3,
  "tribes": [ "Squirrel" ],
  "abilities": [ "Tutor" ],
  "specialAbilities": [],
  "traits": [ "DeathcardCreationNonOption"],
  "texture": "IGCC_looking_heart.png"
}

**Comment by VinsiesPlayer** [comment]
Just edit the JSON, and add "zorro.inscryption.infiniscryption.sidedecks.SideDeck" into metaCategories.

**Comment by scrybeofteeth** [comment]
thanks!

**Comment by divisionbyz0rro** [comment]
The latest version of the Side Deck mod supports a custom metacategory that can be used through JSON Loader. The README for the latest version has all the necessary information:

https://inscryption.thunderstore.io/package/Infiniscryption/Side_Deck_Selector/
