### ISSUE TITLE
P03 starting hand incorrectly overrides the first 3 cards of a Leshy run

### ISSUE THREAD

**Issue by ARandomCatOffTheStreets** [divisionbyz0rro/Infiniscryption#57]
I've had a consistent issue where every time I try to do a Leshy run, the first 3 cards have incorrectly been pulled from P03's starting hand.
![image](https://user-images.githubusercontent.com/35349470/160986085-02e89c30-c2da-4d1e-9b69-3556cd442413.png)

**Comment by divisionbyz0rro** [comment]
Which version of the mod are you running?

**Comment by ARandomCatOffTheStreets** [comment]
1.0.7

**Comment by ARandomCatOffTheStreets** [comment]
It seems to be working properly in the newest update

**Comment by divisionbyz0rro** [comment]
Excellent!
