### ISSUE TITLE
"When a card is killed, a random card is played" softlocks run

### ISSUE THREAD

**Issue by thatguyoversea** [divisionbyz0rro/Infiniscryption#58]
![image](https://user-images.githubusercontent.com/80226671/161269176-1ee109fd-c556-4f9b-bacc-161fc51e606d.png)
You end up just staring at him, and he stares at you. Creepy

**Comment by thatguyoversea** [comment]
Also the text in the console says:
![image](https://user-images.githubusercontent.com/80226671/161269422-7564f681-f2a3-47ef-b0ac-cb1a879166fd.png)

**Comment by divisionbyz0rro** [comment]
Which version of the mod are you running?

**Comment by divisionbyz0rro** [comment]
It looks like you're still running on the Kaycee's Mod beta version of the game. All mods are now targeting the main version of the game since Kaycee's Mod has released for real.
