### ISSUE TITLE
Vanilla Stackable mod optimization

### ISSUE THREAD

**Issue by IllianDeCube09** [divisionbyz0rro/Infiniscryption#59]
Very low fps while displaying cards with this mod enabled.

**Comment by divisionbyz0rro** [comment]
The FPS issue is due to the way that certain card properties are calculated every single frame in the vanilla game. The root cause is actively being investigated in the core API, and that's where we're working on a fix:

https://github.com/InscryptionModding/InscryptionAPI/issues/70
